### ISSUE TITLE
User Extended Fields for K2 type="list" multiple="multiple" bug

### ISSUE THREAD

**Issue by felipeabranches** [getk2/user-extended-fields-for-k2#2]
Hi folks,

I've made some changes in "User Extended Fields for K2" adding a fild type="list" and set the attribute multiple="multiple".

There´s an error when saving this field in database, in "#__k2_users" table, "plugins" field, the value goes as, for example:
...
"userExtendedFieldsexpertise[":"natural",
...
always recording the last value selected only.

If I remove the attribute multiple="multiple", it works fine
...
"userExtendedFieldsexpertise":"life",
...

I'm using:
Joomla 3.4.1
K2 2.6.9
User Extended Fields for K2 3.0

**Comment by fevangelou** [comment]
Do you still get this issue?
